feat(Server): add WebApi hook for plugins
tiltedphoques/CyberpunkMP pull request #43
Opened 2024-12-05 02:51 UTC by poirierlouis

- add `IWebApiHook` interface
- plugin implements a factory `BuildController()` to allow internal DI with controller.
- detect when `IWebApiHook` is declared when listing plugins with Assembly.
- add endpoint `/api/v1/plugins/` to list plugins with a WebApi.
- add controller endpoint `/api/v1/plugins/<name>` in which plugin can add as many endpoints required.

2024-12-05 14:09 UTC, poirierlouis commented
Before:
`EmoteSystem` ---> `/api/v1/plugins/` ---> `["emote"]`

After:
`EmoteSystem` ---> `/api/v1/plugins/` ---> `[{"Name":"emote"}]`

Allow to add extra fields later per plugin, like version/author/widget component path...

2024-12-05 16:30 UTC, poirierlouis commented
Add lock to read/write last triggered emote.

2024-12-08 13:25 UTC, maximegmd approved these changes

2024-12-08 13:26 UTC, maximegmd requested changes

2024-12-08 13:26 UTC, maximegmd commented on code/server/scripting/EmoteSystem/WebApi.cs
> +        if (_plugin.LastEmote == null)
This function is not thread safe, you read LastEmote, check the value, but it could change when returning, you need to cache the value.

2024-12-08 13:26 UTC, maximegmd commented on code/server/scripting/EmoteSystem/Plugin.cs
> +                _lastEmoteLock.EnterReadLock();
why not just use the lock directive?

2024-12-08 13:43 UTC, poirierlouis commented
`lock` is better than I thought!

2024-12-08 20:15 UTC, merged