feat(Launcher): refactor and improve UX
tiltedphoques/CyberpunkMP pull request #8
Opened 2024-11-22 19:49 UTC by poirierlouis

**Implemented:*
WIP

**Preview:**
![image](https://github.com/user-attachments/assets/318a5a4d-9984-4708-8f82-c2dff380fed3)

2024-11-22 21:32 UTC, maximegmd requested changes
The build command should remain ow-electron.

Edit: oops I see this just a rename to simplify, it's fine :)

2024-11-22 21:38 UTC, poirierlouis commented
I'll enable back refresh loop, every 10s this time.

2024-11-22 21:55 UTC, poirierlouis commented
@maximegmd it is ready on my end :)
I'll add some UX stuff in another PR.

2024-11-24 09:50 UTC, maximegmd approved these changes

2024-11-24 09:50 UTC, merged